version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
  addition:
    build: ./landing/app/addition  # path is relative to docker-compose.yml location
    ports:
      - 5051:5051  # host:container
    networks:
      sample:
        aliases:
          - addition
  subtraction:
    build: ./landing/app/subtraction  # path is relative to docker-compose.yml location
    ports:
      - 5052:5052  # host:container
    networks:
      sample:
        aliases:
          - subtraction
  multiplication:
    build: ./landing/app/multiplication  # path is relative to docker-compose.yml location
    ports:
      - 5053:5053  # host:container
    networks:
      sample:
        aliases:
          - multiplication
  division:
    build: ./landing/app/division  # path is relative to docker-compose.yml location
    ports:
      - 5054:5054  # host:container
    networks:
      sample:
        aliases:
          - division
  exponent:
    build: ./landing/app/exponent  # path is relative to docker-compose.yml location
    ports:
      - 5055:5055  # host:container
    networks:
      sample:
        aliases:
          - exponent
  greater_than:
    build: ./landing/app/greater_than  # path is relative to docker-compose.yml location
    ports:
      - 5056:5056  # host:container
    networks:
      sample:
        aliases:
          - greater_than
  less_than:
    build: ./landing/app/less_than  # path is relative to docker-compose.yml location
    ports:
      - 5057:5057  # host:container
    networks:
      sample:
        aliases:
          - less_than
networks:
  sample:   
  